### ISSUE TITLE
Uncaught SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by pjedge** [h3imdall/ftp-remote-edit#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Manjaro Linux"
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.11.7

### Stack Trace

Uncaught SyntaxError: Unexpected token  in JSON at position 0

```
At file:///usr/lib/atom/static/index.html:1

SyntaxError: Unexpected token  in JSON at position 0
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:116:27)
    at FtpRemoteEdit.toggle (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:152:21)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:38:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:166:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1308:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:06.9.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
 17x -1:00.9.0 core:backspace (input.hidden-input)
     -0:50.3.0 core:confirm (input.hidden-input)
     -0:38.6.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
build-make 0.13.0 
busy-signal 1.4.3 
comment 0.6.1 
ftp-remote-edit 0.11.7 
hidpi 0.12.0 
intentions 1.1.2 
language-rust 0.4.10 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.2 
rustfmt 0.1.3 
```

**Comment by pjedge** [comment]
this error happens if I mistype the password upon opening a new session

**Comment by cschindl** [comment]
Hi @pjedge,  @seba2305, @igun997, @uraikus,

I hope I could found the error. Configuration settings will be stored in an encrypted JSON String. Maybe non-valid JSON chars can cause the error when trying to parse the string into an object. I added function to preserve newlines, etc and remove non-printable and other non-valid JSON chars (08b666eb36c83fae50def0122250750f827e0d99)

Changes are available in the next release.

**Comment by cschindl** [comment]
Hi @pjedge, @seba2305, @igun997, @uraikus, @Sofianio,

changes are now available in current release 0.11.11. Can anybody of you please confirm the the changes fixed the reported error.

**Comment by Sofianio** [comment]
I updated but the error still appears when i put in a new session password.
i work with multiple windows but only one session works

file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1
Hide Stack Trace
SyntaxError: Unexpected token � in JSON at position 1
    at Object.parse (native)
    at _TreeView.loadServers (/Users/mememe/.atom/packages/ftp-remote-edit/lib/views/tree-view.js:117:27)
    at FtpRemoteEdit.toggle (/Users/mememe/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:152:21)
    at atom-workspace.ftpRemoteEditToggle (/Users/mememe/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:38:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by cschindl** [comment]
Hi @pjedge, @seba2305, @igun997, @uraikus, @Sofianio, @yyynnn, 

I can not reproduce the error. I tried it with several os and multiple atom instances. Would it be possible for you to create test data that produces the error?

For this, please proceed as follows:

1. Backup your config.json ("File" -> "Config..." -> "Save As..." -> save somewhere on your hdd)
2. Delete all entries from "ftp-remote-edit:" in the config.cson
3. Reboot atom
4. Toggle and enter a test password (for example "123456").
5. Create one or more test servers (the data does not have to be correct or work)
6. Once the error occurs, copy the whole part of "ftp-remote-edit:" from the config.cson and paste it here. Do not forget to enter your test password here as well.
7. Enter steps to reproduce here like in the atom error report 
7. Restore your config.json ("File" -> "Config..." -> copy the contents of the backup back to that file and save)
8. Reboot atom, now all your settings should be available again

I will use the data and try to reproduce the error on my system and hopefully find a way to remove this stupid error :)

**Comment by pjedge** [comment]
haha, figures... I got to step 6 and now I can't reproduce the error, it gives me "wrong password" prompt as it's supposed to. I'll leave the cson entry empty and start fresh, and let you know if I encounter the problem again

**Comment by cukabeka** [comment]
I was asked in #115 to enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Not sure,started happening and since then almost always


Do you use multiple instances of atom at the same time?
No, single

Can you reproduce the error?
No

Did you start with a fresh new installaltion of the plugin?
Afaik yes

Can you add new servers?
When the error occurs, yes

Do you see the tree view when toggle with ctrl + space?
No

**Comment by ozgurcd** [comment]
This happened as soon as I choose "Edit Servers" item from "Packages -> Ftp-Remote-Edit" menu.

**Comment by cschindl** [comment]
I could not identify the problem yet. Either is an error in atom or decryption. To exclude the error in atom, I have added a function that alternatively determines the configuration. 49c1013fe7b390d36d8b928ba439e69fd95aea72

**Comment by cschindl** [comment]
Unfortunately, the last change only caused problems and I removed it. The only way I could reproduce the error was to use a wrong password when decrypting. This caused the result to be nonsense and could not be used anymore.  

I therefore ask for your cooperation:

Have you changed your Master Password in the past?
Have you added new servers where you have inserted the access data via Copy+Paste? (You may have added invalid characters that were not filtered out)

**Comment by cukabeka** [comment]
What if I can't remember any Master Password? When would I have this set and where could I re-Set it. Is this referring to ftp-remote-edit or to atom in general?

**Comment by cschindl** [comment]
Hi @cukabeka 

the master password is set at the first use. All settings including the password are stored in encrypted form in the plugin settings. To reset all settings, simply follow the instructions in this issue https://github.com/h3imdall/ftp-remote-edit/issues/89.

**Comment by cschindl** [comment]
Fixed in 2ac71fddc1b8b0e879057f7ce1d8d0bf15e08def and bb55090db8038c1f259cf9d8a97e373a41f6802c.

**Comment by brandonfrulla** [comment]
Mac OS M1 Air, running Ventura 13.4.1(c):

ReferenceError: configArray is not defined
    at Storage.load (storage.js:56:22)
    at ftp-remote-edit.js:488:23

Triple checked my password, just wanted to share the issue persists for me as well.

**Comment by khallingstad** [comment]
This error is fixed in the latest version 0.20. But the package in Package Manager inside Pulsar Edit, is verison 0.18. 

Just install the latest version using this command in Linux terminal: 
`pulsar -p install https://github.com/h3imdall/ftp-remote-edit`
I had to uninstall Pulsar Edit that I installed from Flatpack, and install normal .rpm package for the pulsar command to work in my Terminal. Working great on my system now.

**Comment by CNHAustin** [comment]
> This error is fixed in the latest version 0.20. But the package in Package Manager inside Pulsar Edit, is verison 0.18.
> 
> Just install the latest version using this command in Linux terminal: `pulsar -p install https://github.com/h3imdall/ftp-remote-edit` I had to uninstall Pulsar Edit that I installed from Flatpack, and install normal .rpm package for the pulsar command to work in my Terminal. Working great on my system now.

Confirming that updating to newest version (0.20) solves this issue. I installed from the Package Manager in the pulsar website, then after a restart of the app, the _in app_ Package Manager prompted me to update to 0.20.

Works great!
